# Generated by Django 5.0.6 on 2024-07-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_conversation_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
