# Generated by Django 5.0.6 on 2024-07-07 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_conversation_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='active',
            new_name='new',
        ),
    ]
