# Generated by Django 5.0.6 on 2024-07-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_conversation_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='customer_service_user',
            new_name='employee',
        ),
    ]
